### ISSUE TITLE
2015-09-19 study issue

### ISSUE THREAD

**Issue by shepherd44** [iamroot11B/linux_stable_3_14_4#17]
exception table이란?
커널 익셉션 테이블(exception table) 이란 커널 모드에서 사용자 공간의 데이터에 접근이 실패한 경우, 이를 처리해주기 위한 핸들러가 위치한 엔트리 (fixup handler entry)를 말한다.
interrupt table과의 차이점

**Comment by tttuuu888** [comment]
커널 시스템 콜 관련
http://forum.falinux.com/zbxe/index.php?mid=lecture_tip&page=62&document_srl=574604
