### ISSUE TITLE
2015-10-24 study issue

### ISSUE THREAD

**Issue by tttuuu888** [iamroot11B/linux_stable_3_14_4#18]
슬랩 할당자 관련 참조
http://www.test104.com/kr/tech/1878.html

 kmem_cache_create를 위한 옵션 일부 목록 (플래그로 명시)

옵션 설명

SLAB_RED_ZONE 버퍼 넘침을 점검하기 위해 객체 헤더와 트레일러에 특수한 표식을 집어넣는다.

SLAB_POISON (캐시가 소유한 객체를 외부에서 수정했는지 검사하기 위해) 캐시에서 객체를 감시하기 위해 알려진 패턴으로 슬랩을 채운다.

SLAB_HWCACHE_ALIGN이 캐시에 있는 객체가 하드웨어 캐시 라인에 맞춰 정렬되어야 함을 지시한다.

ctor 와 dtor 매개변수는 부가적인 객체 생성자와 소멸자를 정의한다. 생성자와 소멸자는 사용자가 제공하는 콜백 함수다. 새로운 객체를 캐시에서 할당할 때 생성자를 통해 초기화 할 수 있다.

캐시 생성 후 참조 값은 kmem_cache_create 함수가 반환한다. 이 함수는 캐시에 메모리를 할당하지 않음에 주목하자. 그 대신 캐시에서 객체를 할당하려는 시도가 일어날 때 (초기에는 비어 있다), refill 연산을 통해 메모리를 할당한다. 모든 객체를 다 썼을 때나 캐시에 메모리를 추가 할 때도 같은 연산을 이용한다. 

kmem_cache_destroy

커널 함수인  kmem_cache_destroy 는 캐시를 소멸 시킬 때 사용한다. 이 함수는 메모리에서 내려올 때 커널 모듈이 호출한다. 이 함수 호출 전에 캐시는 비어 있어야 한다.

void kmem_cache_destroy( struct kmem_cache *cachep );

**Comment by GPRESean** [comment]
Poisoning의 동작에 관해
https://whatilearned2day.wordpress.com/2006/12/13/slab-poisoning/

If you have an offending address 0xa5a5a5a5 somewhere in the kernel oops message, you can be almost be sure that you have used an uninitialized dynamically allocated memory somewhere. Similarl, if you see some where the address 0x6b6b6b6b, you can very much be sure of using a freed variable.

**Comment by GPRESean** [comment]
SLAB, SLOB, SLUB의 특징
http://studyfoss.egloos.com/5332580
