### ISSUE TITLE
2016-01-23 study issue

### ISSUE THREAD

**Issue by GPRESean** [iamroot11B/linux_stable_3_14_4#21]
cmpxchg는 lock 없이 atomic 연산을 하는 기법에 활용한다.

https://courses.engr.illinois.edu/ece390/archive/spr2002/books/labmanual/inst-ref-cmpxchg.html

**Comment by GPRESean** [comment]
slab, slub의 metadata란?

http://devcry.heiho.net/html/2015/20150111-mm-slub.html

But what about the metadata? SLUB puts the free pointers inside the memory slots. The objects are free, so this memory is available for us to use. 
The other metadata (like, where is the first free object? What is my object size?) is kept in a Page struct. All pages in memory are tracked by an array of Page struct. Beware the confusion here, a Page struct is not the actual memory page, it just represents the metadata for that memory page.

**Comment by tttuuu888** [comment]
kmem_cahce_node   구조 그림
![kmem_cache_nod](https://cloud.githubusercontent.com/assets/8042298/12530001/b3e335c8-c211-11e5-8c94-1d2e0aa93a30.gif)

**Comment by GPRESean** [comment]
slab, slub의 상태

상태: empty, partial, full
* 모든 object가 free -> empty 상태
* 일부 object가 used -> partial 상태
* 모든 object가 used -> full 상태

**Comment by SongChiYoung** [comment]
first chunk가 할당되고 나면 pcpu_setup_first_chunk() 함수가 호출되어 다음과 같은 percpu에 관련된 정보들을 모두 저장해 두고 이 후의 할당 시에 참조하도록 한다.

* pcpu_base_addr: first chunk가 할당된 가상 주소
* pcpu_nr_groups: percpu group의 수 (NUMA node의 수)
* pcpu_group_offsets: 각 group의 시작 offset을 저장한 테이블
* pcpu_group_sizes: 각 group의 크기를 저장한 테이블
* pcpu_nr_units: percpu unit의 수 (CPU의 수)
* pcpu_unit_map: cpu 번호를 통해 unit 번호를 알아내기 위한 테이블
* pcpu_unit_offsets: 각 unit의 시작 offset을 저장한 테이블
* pcpu_unit_size: unit의 크기
* pcpu_atom_size: page 할당을 위한 최소 단위
* pcpu_nr_slots: chunk 관리를 위한 slot의 수

http://studyfoss.egloos.com/5377666

**Comment by GPRESean** [comment]
[20160123_스터디_백업.zip](https://github.com/iamroot11B/linux_stable_3_14_4/files/101865/20160123_._.zip)
