### ISSUE TITLE
2016-05-21

### ISSUE THREAD

**Issue by SongChiYoung** [iamroot11B/linux_stable_3_14_4#27]

**Comment by SongChiYoung** [comment]
http://egloos.zum.com/studyfoss/v/5375570

    83 #define __addr_to_pcpu_ptr(addr)                                        \
    84         (void __percpu *)((unsigned long)(addr) -                       \
    85                           (unsigned long)pcpu_base_addr +               \
의 의미는??

__percpu: (3) percpu 주소 공간. 정적으로 할당된 percpu 영역의 경우 컴파일 된 이미지 상의 심볼 주소와 실제로 메모리가 할당된 주소가 다르며, 동적으로 할당된 경우라도 cpu에 따라 실제 존재하는 위치가 다르므로 반드시 per_cpu, get_cpu_var 등의 함수/매크로를 통해서 접근해야 한다.

**Comment by plus2004** [comment]
percpu 참고 이미지 ( 아래  URL 하단의 이미지 )
http://www.programering.com/a/MDN4UzNwATU.html
