### ISSUE TITLE
Start_Kernel 종료 후 다시 볼 부분들

### ISSUE THREAD

**Issue by tttuuu888** [iamroot11B/linux_stable_3_14_4#32]
## update_wall_time(timekeeping.c)
real timekeeper를 업데이트 하는 부분. NTP와 클락 간격 간의 누적 오차를 계산하는 등 복잡한 계산이 많이 들어간다.

**Comment by SongChiYoung** [comment]
__schdule()

해당 함수는 vfs 이후에 보도록 한다.

**Comment by SongChiYoung** [comment]
asmlinkage void dump_stack(void)
굳이 내용을 일찍 볼 필요 없어보임

**Comment by tttuuu888** [comment]
netlink_broadcast_filtered 이하 net 관련 내용 자세히 안 봄

**Comment by tttuuu888** [comment]
fs/locks.c의 posix_lock_file 함수 아래 단계는 추후에 보기로 함

**Comment by GPRESean** [comment]
8/26 ARM 11차 B조 스터디 끝.
1주 추가 스터디에서는 아래 두가지를 드라이브 합니다.

kernel/sched/core.c
__schedule()

kernel/fork.c
do_fork()

**Comment by tttuuu888** [comment]
2017. 9.16 __schedule() 추가 스터디를 마지막으로 스터디 종료
