### ISSUE TITLE
2015-04-18 Study

### ISSUE THREAD

**Issue by SongChiYoung** [iamroot11B/linux_stable_3_14_4#4]

**Comment by SongChiYoung** [comment]
lockdep ?  http://egloos.zum.com/studyfoss/v/5342153

**Comment by SongChiYoung** [comment]
wait queue? http://forum.falinux.com/zbxe/index.php?document_srl=565499&mid=lecture_tip

**Comment by shepherd44** [comment]
kswapd란? http://cluster1.cafe.daum.net/_c21_/bbs_search_read?grpid=1K80b&fldid=7F3b&datanum=20&contentval=&docid=1K80b7F3b2020100313203129

**Comment by shepherd44** [comment]
__mod_zone_page_state? http://manseok.blogspot.kr/search?q=mod_zone_page_state
